# Generated by Django 4.1.1 on 2022-12-04 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="feedback_text_response",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
