# Generated by Django 4.1.1 on 2022-12-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0003_cars_car_condition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupons",
            name="date_valid_from",
        ),
        migrations.RemoveField(
            model_name="coupons",
            name="date_valid_to",
        ),
    ]
