# Generated by Django 4.1.1 on 2022-12-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0005_feedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
