# Generated by Django 4.1.1 on 2022-12-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0006_delete_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="car_condition",
            field=models.BooleanField(),
        ),
    ]
