# Generated by Django 4.1.1 on 2022-12-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0007_alter_cars_car_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="subscription",
            field=models.CharField(default=0, max_length=1),
        ),
    ]
