# Generated by Django 4.1.1 on 2022-12-05 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("owner", "0007_alter_cars_car_condition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book_Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity", models.CharField(max_length=3)),
                ("from_date", models.DateTimeField()),
                ("to_date", models.DateTimeField()),
                ("rent", models.FloatField()),
                ("is_paid", models.BooleanField(default=False)),
                ("confirmation", models.CharField(default=0, max_length=1)),
                ("booked_date", models.DateTimeField(auto_now_add=True)),
                ("confirmed_date", models.DateTimeField(auto_now=True)),
                (
                    "car_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="owner.cars"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
