# Generated by Django 4.1.1 on 2022-12-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book_car",
            name="car_id",
        ),
    ]
