# Generated by Django 4.1.1 on 2022-12-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0009_cars_cost_of_vehicle_cars_rent_per_hour_and_more"),
        ("booking", "0003_alter_book_car_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_car",
            name="car",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="owner.cars",
            ),
            preserve_default=False,
        ),
    ]
