# Generated by Django 4.1.1 on 2022-12-06 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_remove_book_car_car"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book_car",
            old_name="user_id",
            new_name="user",
        ),
    ]
