# Generated by Django 4.1.1 on 2022-12-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="area",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
        migrations.RemoveField(
            model_name="customerupdate",
            name="area",
        ),
        migrations.DeleteModel(
            name="Area",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="CustomerUpdate",
        ),
    ]
