# Generated by Django 4.1.1 on 2022-12-05 19:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Appointment",
            new_name="Appointment_data",
        ),
    ]
