# Generated by Django 4.1.1 on 2022-12-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_rename_appointment_appointment_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment_data",
            name="appointment",
            field=models.CharField(max_length=30),
        ),
    ]
